export const CACHE_SECONDS=900;
export const STALE_SECONDS=5400;
export const TREND_DEADBAND_FT=0.03;

export function parseUSGSFeatures(features){const out={water_level:null,streamflow:null,observed_at:null,freshness_at:null};for(const f of features||[]){const p=f.properties||{};const value=Number(p.value);if(!Number.isFinite(value)||!p.time)continue;let key=null;if(p.parameter_code==='00065')key='water_level';if(p.parameter_code==='00060')key='streamflow';if(!key)continue;const obs={value,unit:p.unit_of_measure||'',observed_at:p.time,quality_status:p.approval_status||null};const existing=out[key];if(!existing||Date.parse(obs.observed_at)>Date.parse(existing.observed_at))out[key]=obs;}const times=[out.water_level?.observed_at,out.streamflow?.observed_at].filter(Boolean);if(times.length){out.observed_at=times.reduce((a,b)=>Date.parse(a)>Date.parse(b)?a:b);}if(times.length===2){out.freshness_at=times.reduce((a,b)=>Date.parse(a)<Date.parse(b)?a:b);}return out;}

export function calculateTrend(features){const points=(features||[]).filter(f=>f?.properties?.parameter_code==='00065'&&Number.isFinite(Number(f.properties.value))&&f.properties.time).map(f=>({value:Number(f.properties.value),time:f.properties.time})).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));if(points.length<2)return'unknown';const newest=points.at(-1);const candidates=points.slice(0,-1).map(point=>({point,age:(Date.parse(newest.time)-Date.parse(point.time))/60000})).filter(item=>item.age>=45&&item.age<=75).sort((a,b)=>Math.abs(a.age-60)-Math.abs(b.age-60));if(!candidates.length)return'unknown';const delta=newest.value-candidates[0].point.value;if(Math.abs(delta)<=TREND_DEADBAND_FT)return'steady';return delta>0?'rising':'falling';}

export function freshness(observedAt,now=Date.now()){if(!observedAt)return'unavailable';const age=(now-Date.parse(observedAt))/1000;if(age<=1800)return'fresh';if(age<=STALE_SECONDS)return'delayed';return'unavailable';}
export function json(data,status=200,origin=''){const headers={'content-type':'application/json; charset=utf-8','cache-control':`public, max-age=${CACHE_SECONDS}, s-maxage=${CACHE_SECONDS}`};if(origin)headers['access-control-allow-origin']=origin;return new Response(JSON.stringify(data),{status,headers});}
